// @ts-check
// Fetch, transform and fingerprint every third-party asset listed in
// assets/manifest.json. DEV-TIME ONLY — the game never downloads anything; it
// serves what this tool committed. Needs the network and the `sharp`
// devDependency.
//
//   node tools/fetch-assets.mjs                 fetch whatever is missing or stale
//   node tools/fetch-assets.mjs <id> [<id>…]    only these entries
//   node tools/fetch-assets.mjs --force <id>    re-fetch even if the files verify
//   node tools/fetch-assets.mjs --verify        check every file's sha256; download nothing
//   node tools/fetch-assets.mjs --list <id>     print the models inside a gltf entry's zip
//
// Idempotent: an entry whose files already match their recorded sha256 is
// skipped without a request. Downloads are cached under node_modules/.cache/
// (git-ignored), so re-running after a transform tweak does not re-download.
//
// Transforms, per entry kind:
//   hdri  copied byte for byte (Poly Haven's .hdr is already the size we want)
//   pbr   sharp resize to transform.size (1024), JPEG transform.quality (82;
//         normals transform.normalQuality, 90), and AO / roughness / metalness
//         packed into ONE `_orm` texture (R/G/B, the glTF layout three's aoMap,
//         roughnessMap and metalnessMap already read): 3 files a set, not 5
//   gltf  unzip, pick models by transform.pick [{as, match}], copy every external
//         buffer/image a picked model references, and rename the model to `as`
//   lut   generated by tools/lib/lut.mjs (transform.generate, transform.size)
//
// Every path that comes out of a downloaded zip — entry names and the URIs inside
// the models — goes through safeRelative() (tools/lib/safePath.mjs) before it is joined onto anything, and
// every write is checked to land under assets/: a hostile or broken archive must
// not be able to write outside the pipeline's directories (zip-slip).
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, normalize, posix, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { readZip } from './lib/archive.mjs';
import { safeRelative } from './lib/safePath.mjs';
import { validateManifest, verifyFiles, totalBytes, sha256, ASSET_BUDGET_BYTES } from './lib/manifest.mjs';
import { cubeText, GRADES, LUT_SIZE } from './lib/lut.mjs';
import { pickModel, externalUris } from './lib/gltfPick.mjs';
import { packOrm } from './lib/pbrPack.mjs';

const ROOT = normalize(join(fileURLToPath(import.meta.url), '..', '..'));
const ASSETS = resolve(ROOT, 'assets');
const MANIFEST = join(ROOT, 'assets', 'manifest.json');
const CACHE = join(ROOT, 'node_modules', '.cache', 'ncld-assets');
const DOWNLOAD_TIMEOUT_MS = 60_000;
const mb = (n) => (n / 1048576).toFixed(2);

/** @param {string} url */
async function download(url) {
  const cached = join(CACHE, createHash('sha256').update(url).digest('hex').slice(0, 24));
  if (existsSync(cached)) return readFile(cached);
  console.log(`    ↓ ${url}`);
  // A stalled CDN must fail the run, not hang it — and say which URL stalled.
  let buf;
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'neon-city-lock-down fetch-assets' },
      signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
    });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
    buf = Buffer.from(await res.arrayBuffer());
  } catch (err) {
    if (err instanceof Error && err.name === 'TimeoutError') throw new Error(`timed out after ${DOWNLOAD_TIMEOUT_MS / 1000} s: ${url}`);
    throw err;
  }
  await mkdir(CACHE, { recursive: true });
  await writeFile(cached, buf);
  return buf;
}

/** @param {string} id @param {ReturnType<typeof readZip>} zip */
function reportRejected(id, zip) {
  for (const r of zip.rejected) console.error(`  ✗ ${id}: skipped ${r.reason}`);
}

/**
 * The absolute path a repo-relative output path writes to, or a throw if it would
 * land outside assets/. Belt and braces over safeRelative() at the zip boundary.
 * @param {string} rel
 */
function assetTarget(rel) {
  const abs = resolve(ROOT, safeRelative(rel));
  if (!abs.startsWith(ASSETS + sep)) throw new Error(`refusing to write "${rel}": outside assets/`);
  return abs;
}

/** @typedef {{path:string, role:string, name?:string, buf:Buffer}} Output */

/** @type {Record<string, (entry:any) => Promise<Output[]>>} */
const HANDLERS = {
  async hdri(entry) {
    return [{ path: `assets/hdri/${entry.id}.hdr`, role: 'hdr', buf: await download(entry.urls.hdr) }];
  },

  async pbr(entry) {
    const sharp = (await import('sharp')).default;
    const S = entry.transform.size ?? 1024;
    const q = entry.transform.quality ?? 82;
    const jpeg = (buf, quality = q) => sharp(buf).resize(S, S, { fit: 'fill' }).jpeg({ quality }).toBuffer();
    const channel = (buf) => sharp(buf).resize(S, S, { fit: 'fill' }).extractChannel(0).raw().toBuffer();
    const u = entry.urls;
    const dir = `assets/pbr/${entry.id}`;
    const out = [
      { path: `${dir}/${entry.id}_diff.jpg`, role: 'diff', buf: await jpeg(await download(u.diff)) },
      { path: `${dir}/${entry.id}_nor.jpg`, role: 'nor', buf: await jpeg(await download(u.nor), entry.transform.normalQuality ?? 90) },
    ];
    let orm;
    if (u.arm) {
      orm = await jpeg(await download(u.arm));   // Poly Haven's ARM is already AO/rough/metal in R/G/B
    } else {
      const [ao, rough, metal] = await Promise.all([
        u.ao ? download(u.ao).then(channel) : null,
        download(u.rough).then(channel),
        u.metal ? download(u.metal).then(channel) : null,
      ]);
      orm = await sharp(packOrm({ size: S, ao, rough, metal }), { raw: { width: S, height: S, channels: 3 } })
        .jpeg({ quality: q }).toBuffer();
    }
    out.push({ path: `${dir}/${entry.id}_orm.jpg`, role: 'orm', buf: orm });
    entry.hasMetal = Boolean(u.metal || u.arm);
    return out;
  },

  async gltf(entry) {
    const zip = readZip(await download(entry.urls.zip));
    reportRejected(entry.id, zip);
    const names = zip.entries.map((e) => e.name);
    const packDir = `assets/props/${entry.id}/`;
    /** @type {Output[]} */
    const out = [];
    const seen = new Set();
    for (const { as, match } of entry.transform.pick) {
      if (!/^[a-z0-9_]+$/.test(as)) throw new Error(`${entry.id}: pick name "${as}" must match [a-z0-9_]+`);
      const src = pickModel(names, match);
      if (!src) throw new Error(`${entry.id}: no model matches "${match}" — run: node tools/fetch-assets.mjs --list ${entry.id}`);
      const ext = posix.extname(src).toLowerCase();
      const buf = zip.read(src);
      out.push({ path: `${packDir}${as}${ext}`, role: 'model', name: as, buf });
      for (const uri of externalUris(buf, ext)) {
        try { safeRelative(uri); } catch (err) { throw new Error(`${entry.id}/${as}: refusing URI "${uri}": ${err instanceof Error ? err.message : err}`); }
        const from = posix.normalize(posix.join(posix.dirname(src), uri));
        const to = posix.normalize(`${packDir}${uri}`);
        if (!to.startsWith(packDir)) throw new Error(`${entry.id}/${as}: "${uri}" points outside the pack directory`);
        if (seen.has(to)) continue;
        seen.add(to);
        if (!names.includes(from)) throw new Error(`${entry.id}/${as}: references ${uri}, which is not in the zip`);
        out.push({ path: to, role: 'dependency', buf: zip.read(from) });
      }
    }
    return out;
  },

  async lut(entry) {
    const grade = GRADES[entry.transform.generate];
    if (!grade) throw new Error(`${entry.id}: unknown grade "${entry.transform.generate}"`);
    const text = cubeText({ title: entry.id, size: entry.transform.size ?? LUT_SIZE, grade });
    return [{ path: `assets/luts/${entry.id}.cube`, role: 'cube', buf: Buffer.from(text) }];
  },
};

async function main() {
  const args = process.argv.slice(2);
  const manifest = JSON.parse(await readFile(MANIFEST, 'utf8'));

  if (args[0] === '--list') {
    const e = manifest.entries.find((x) => x.id === args[1]);
    if (!e || e.kind !== 'gltf') throw new Error(`--list needs a gltf entry id (got "${args[1] ?? ''}")`);
    const zip = readZip(await download(e.urls.zip));
    reportRejected(e.id, zip);
    for (const n of zip.entries.map((x) => x.name).filter((n) => /\.(glb|gltf)$/i.test(n)).sort()) console.log(n);
    return;
  }

  if (args.includes('--verify')) {
    const errs = [...validateManifest(manifest), ...await verifyFiles(manifest, ROOT)];
    for (const e of errs) console.error(`  ✗ ${e}`);
    console.log(`${errs.length ? 'FAILED' : 'ok'} — ${manifest.entries.length} entries, ${mb(totalBytes(manifest))} MB of ${mb(ASSET_BUDGET_BYTES)} MB`);
    if (errs.length) process.exitCode = 1;
    return;
  }

  const force = args.includes('--force');
  const ids = args.filter((a) => !a.startsWith('--'));
  const unknown = ids.filter((id) => !manifest.entries.some((e) => e.id === id));
  if (unknown.length) throw new Error(`unknown id(s): ${unknown.join(', ')}`);

  for (const entry of manifest.entries) {
    if (ids.length && !ids.includes(entry.id)) continue;
    const fresh = entry.files?.length > 0 && (await verifyFiles({ entries: [entry] }, ROOT)).length === 0;
    if (fresh && !force) { console.log(`  = ${entry.id} (up to date)`); continue; }
    const handler = HANDLERS[entry.kind];
    if (!handler) throw new Error(`${entry.id}: no handler for kind "${entry.kind}"`);
    console.log(`  ▸ ${entry.id}`);
    const outputs = await handler(entry);
    entry.files = [];
    for (const o of outputs) {
      const abs = assetTarget(o.path);
      await mkdir(dirname(abs), { recursive: true });
      await writeFile(abs, o.buf);
      entry.files.push({ path: o.path, role: o.role, ...(o.name ? { name: o.name } : {}), bytes: o.buf.length, sha256: sha256(o.buf) });
    }
    entry.files.sort((a, b) => a.path.localeCompare(b.path));
    console.log(`    ${entry.files.length} file(s), ${mb(entry.files.reduce((n, f) => n + f.bytes, 0))} MB`);
  }

  await writeFile(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`\n${mb(totalBytes(manifest))} MB of the ${mb(ASSET_BUDGET_BYTES)} MB budget`);
  const errs = validateManifest(manifest);
  for (const e of errs) console.error(`  ✗ ${e}`);
  if (errs.length) process.exitCode = 1;
}

main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; });
